swagger: '2.0'
info:
  title: DokTool - API - Prompt
  description: ''
  version: '1.0'
host: sp-doktool-prompt.azurewebsites.net
basePath: /
schemes:
  - https
consumes: []
produces: []
paths:
  /api/prompt:
    get:
      responses:
        default:
          description: default
          schema:
            type: object
            properties:
              status:
                type: string
                description: status
              responses:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: id
                    name:
                      type: string
                      description: name
                    prompts:
                      type: array
                      items:
                        type: object
                        properties:
                          role:
                            type: string
                            description: role
                          prompt:
                            type: string
                            description: prompt
                      description: prompts
                    _rid:
                      type: string
                      description: _rid
                    _self:
                      type: string
                      description: _self
                    _etag:
                      type: string
                      description: _etag
                    _attachments:
                      type: string
                      description: _attachments
                    _ts:
                      type: integer
                      format: int32
                      description: _ts
                description: responses
              method:
                type: string
                description: method
              config:
                type: object
                properties:
                  COSMOS_URL:
                    type: string
                    description: COSMOS_URL
                  COSMOS_DATABASE:
                    type: string
                    description: COSMOS_DATABASE
                  COSMOS_CONTAINER:
                    type: string
                    description: COSMOS_CONTAINER
                description: config
      summary: get
      operationId: get
      parameters:
        - name: ID
          in: query
          required: false
          type: string
          x-ms-visibility: internal
      x-ms-visibility: internal
    delete:
      responses:
        default:
          description: default
          schema: {}
      summary: delete
      operationId: delete
      parameters:
        - name: id
          in: query
          required: false
          type: string
    post:
      responses:
        default:
          description: default
          schema: {}
      summary: create
      operationId: create
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              id:
                type: string
                description: id
                title: ID
                x-ms-visibility: internal
              name:
                type: string
                description: name
                title: Name
                x-ms-visibility: internal
              prompts:
                type: array
                items:
                  type: object
                  properties:
                    role:
                      type: string
                      description: role
                      title: Role
                      x-ms-visibility: internal
                      enum:
                        - system
                        - assistant
                        - user
                    prompt:
                      type: string
                      description: prompt
                      title: Prompt
                      x-ms-visibility: internal
                description: prompts
            x-ms-visibility: internal
          x-ms-visibility: internal
    put:
      responses:
        default:
          description: default
          schema: {}
      summary: update
      operationId: update
      parameters:
        - name: id
          in: query
          required: false
          type: integer
        - name: body
          in: body
          required: false
          schema:
            type: object
            properties:
              prompt:
                type: string
                description: prompt
              name:
                type: string
                description: name
              role:
                type: string
                description: role
definitions: {}

parameters:
  prompt:
    name: prompt
    in: body
    description: ''
    schema: {}
  id:
    name: id
    in: path
    required: true
    type: string
    description: ''

responses:
  code:
    description: ''
securityDefinitions: {}
security: []
tags: []
